delete from model;
delete from category;
delete from element;
insert into model (id,name,description) values (1,'Химический элемент','логико-смысловая модель"Химический элемент" типа "Свойстов" уровня "Сущность"');
insert into category (id,name,modelid) values (1,'Положение в ПСХЭ',1);
insert into category (id,name,modelid) values (2,'Состав атома',1);
insert into category (id,name,modelid) values (3,'Электронное строение атома',1);
insert into category (id,name,modelid) values (4,'Характеристика атома',1);
insert into category (id,name,modelid) values (5,'Характеристика ВЭУ',1);
insert into category (id,name,modelid) values (6,'Формула существования элемента',1);
insert into category (id,name,modelid) values (7,'Нахождение в природе',1);
insert into category (id,name,modelid) values (8,'Гуманитарный фон',1);
insert into element (name,categoryid) values ('Символ',1);
insert into element (name,categoryid) values ('Номер периода',1);
insert into element (name,categoryid) values ('Номер группы',1);
insert into element (name,categoryid) values ('Z',1);
insert into element (name,categoryid) values ('N(e)',2);
insert into element (name,categoryid) values ('N(n)',2);
insert into element (name,categoryid) values ('N(p)',2);
insert into element (name,categoryid) values ('Характер элемента',3);
insert into element (name,categoryid) values ('Семейство',3);
insert into element (name,categoryid) values ('Электронная конфигурация',3);
insert into element (name,categoryid) values ('Океслительно-восстановительные свойства',4);
insert into element (name,categoryid) values ('CO',4);
insert into element (name,categoryid) values ('X',4);
insert into element (name,categoryid) values ('Радиус',4);
insert into element (name,categoryid) values ('Ar',4);
insert into element (name,categoryid) values ('N(e)несп.*',5);
insert into element (name,categoryid) values ('Эл. формула*',5);
insert into element (name,categoryid) values ('N(e) несп.',5);
insert into element (name,categoryid) values ('Эл-граф. формула',5);
insert into element (name,categoryid) values ('Классы органических веществ',6);
insert into element (name,categoryid) values ('Формула водородного соединения',6);
insert into element (name,categoryid) values ('Формула и характер высшего гидроксида',6);
insert into element (name,categoryid) values ('Формула и характер высшего оксида',6);
insert into element (name,categoryid) values ('Формула и характер простого вещества',6);
insert into element (name,categoryid) values ('Космос',7);
insert into element (name,categoryid) values ('Атмосфера',7);
insert into element (name,categoryid) values ('Гидросфера',7);
insert into element (name,categoryid) values ('Литосфера',7);
insert into element (name,categoryid) values ('Значение элемента',8);
insert into element (name,categoryid) values ('Этимология названия',8);
insert into element (name,categoryid) values ('Обстоятельства открытия',8);
insert into element (name,categoryid) values ('Время и место открытия',8);
insert into element (name,categoryid) values ('Автор открытия',8);