
update model set object='Химический элемент' where id=1;
insert into model (id,name,description,object) values (2,'Простое вещество','логико-смысловая модель"Простое вещество" типа "Свойстов" уровня "Сущность"','Простое вещество');
insert into category (id,name,modelid) values (9,'Состав и строение',2);
insert into category (id,name,modelid) values (10,'Реакционная способность',2);
insert into category (id,name,modelid) values (11,'Физические свойства',2);
insert into category (id,name,modelid) values (12,'Химические свойства',2);
insert into category (id,name,modelid) values (13,'Применение',2);
insert into category (id,name,modelid) values (14,'Способы получения',2);
insert into category (id,name,modelid) values (15,'физиологическое действие',2);
insert into category (id,name,modelid) values (16,'Гуманитарный фон',2);
insert into element (name,categoryid,modelid) values ('Формула',9,2);
insert into element (name,categoryid,modelid) values ('Вид связи',9,2);
insert into element (name,categoryid,modelid) values ('Вид кристалической решетки',9,2);
insert into element (name,categoryid,modelid) values ('В периоде',10,2);
insert into element (name,categoryid,modelid) values ('В группе',10,2);
insert into element (name,categoryid,modelid) values ('Агрегатное состояние',11,2);
insert into element (name,categoryid,modelid) values ('Цвет',11,2);
insert into element (name,categoryid,modelid) values ('Растворимость',11,2);
insert into element (name,categoryid,modelid) values ('Пловность',11,2);
insert into element (name,categoryid,modelid) values ('t пл',11,2);
insert into element (name,categoryid,modelid) values ('t кип',11,2);
insert into element (name,categoryid,modelid) values ('Особые свойства',11,2);
insert into element (name,categoryid,modelid) values ('Простые вещества',12,2);
insert into element (name,categoryid,modelid) values ('Э2Оn',12,2);
insert into element (name,categoryid,modelid) values ('M(OH)n',12,2);
insert into element (name,categoryid,modelid) values ('H+',12,2);
insert into element (name,categoryid,modelid) values ('MnЭOn',12,2);
insert into element (name,categoryid,modelid) values ('Органические вещества',12,2);
insert into element (name,categoryid,modelid) values ('Быт',13,2);
insert into element (name,categoryid,modelid) values ('Сельское хозяйство',13,2);
insert into element (name,categoryid,modelid) values ('Медицина',13,2);
insert into element (name,categoryid,modelid) values ('Промышленность',13,2);
insert into element (name,categoryid,modelid) values ('Особые области',13,2);
insert into element (name,categoryid,modelid) values ('Лабораторный',14,2);
insert into element (name,categoryid,modelid) values ('Промышленный',14,2);
insert into element (name,categoryid,modelid) values ('Физиологическое действие',15,2);
insert into element (name,categoryid,modelid) values ('Окружающая среда',16,2);
insert into element (name,categoryid,modelid) values ('Художественная литература',16,2);
insert into element (name,categoryid,modelid) values ('Искусство',16,2);

